### ISSUE TITLE
Trouble compiling using nRF Connect SDK v2.1.99-dev2

### ISSUE THREAD

**Issue by twonius** [nobodyguy/HX711_zephyr_driver#1]
I'm trying to add the HX711 driver to the peripheral_hr sample application provided with the nRF-SDK. 

Modifying the manifest and running the west update competes without issue as far as I can tell 

> Executing task: nRF Connect: west update 
> 
> west update
> 
> === updating sdk-nrf (nrf):
> HEAD is now at 5daa9cf8 version: Update to 2.1.99-dev2
> === updating zephyr (zephyr):
> HEAD is now at d4b8ac4db1 [nrf noup] net: wifi: Add support for WPA supplicant
> === updating HX711 (modules/HX711):
> --- HX711: fetching, need revision main
> From https://github.com/nobodyguy/HX711_zephyr_driver
>  * branch            main       -> FETCH_HEAD
> HEAD is now at 8d44614 Code formatting
> === updating sdk-hostap (modules/lib/hostap):
> HEAD is now at 306b36c1f Remove nRF Wi-Fi management
> === updating mcuboot (bootloader/mcuboot):
> HEAD is now at bf00840a [nrf noup] boot: zephyr: Align serial recovery config on Thingy:91
> === updating mbedtls-nrf (mbedtls):
> HEAD is now at d540e87d6 [nrf fromtree] Changelog rewording
> === updating nrfxlib (nrfxlib):
> HEAD is now at 303b506e softdevice_controller: rev 3ca8afffb1f25c6f2e8f119913d74c3e8d482d62
> === updating trusted-firmware-m (modules/tee/tf-m/trusted-firmware-m):
> HEAD is now at 11b5f0a9 [nrf fromlist] platform: nordic_nrf: Move device configuration files
> === updating tfm-mcuboot (modules/tee/tfm-mcuboot):
> HEAD is now at 4aa516e7 Bump versions for v1.7.2
> === updating matter (modules/lib/matter):
> HEAD is now at 6cfff0482 [nrf fromtree] Fix BDX transfer resumption
> Synchronizing submodule url for 'third_party/nlio/repo'
> Synchronizing submodule url for 'third_party/nlassert/repo'
> Synchronizing submodule url for 'third_party/nlunit-test/repo'
> Synchronizing submodule url for 'third_party/pigweed/repo'
> === updating cjson (modules/lib/cjson):
> HEAD is now at c6af068 [nrf fromtree] fix: potential memory leak in merge_patch() (#611)
> === updating azure-sdk-for-c (modules/lib/azure-sdk-for-c):
> HEAD is now at 308c171c [nrf fromlist] Make repository a Zephyr module
> === updating cmock (test/cmock):
> HEAD is now at f65066f Merge pull request #404 from tz18/patch-1
> Synchronizing submodule url for 'vendor/c_exception'
> Synchronizing submodule url for 'vendor/unity'
> === updating memfault-firmware-sdk (modules/lib/memfault-firmware-sdk):
> HEAD is now at 0cf1078 Memfault Firmware SDK 0.33.2 (Build 512901)
> === updating cirrus (modules/hal/cirrus-logic):
> HEAD is now at 9f6b381 sdk-mcu-drivers: Added build system configs and generated files
> === updating openthread (modules/lib/openthread):
> HEAD is now at d3e00fbd2 [dns] allow partial read of TXT data and add config for max size in CLI (#8232)
> === updating canopennode (modules/lib/canopennode):
> HEAD is now at 53d3415 Merge pull request #5 from teslabs/module-name
> === updating chre (modules/lib/chre):
> HEAD is now at ef76d345 Merge pull request #4 from fabiobaltieri/chre-uprev
> === updating cmsis (modules/hal/cmsis):
> HEAD is now at 5f86244 DSP: Fix vector type mismatches
> === updating edtt (tools/edtt):
> HEAD is now at 1ea61a3 Fixing error in DLE test cases
> === updating fatfs (modules/fs/fatfs):
> HEAD is now at a30531a zephyr: update include paths to use <zephyr/...>
> === updating hal_nordic (modules/hal/nordic):
> HEAD is now at f6628a3 include: add "zephyr/" include prefix
> === updating hal_st (modules/hal/st):
> HEAD is now at 52a522c sensor/stmemsc: Align stmemsc i/f to v2.01
> === updating libmetal (modules/hal/libmetal):
> HEAD is now at 2f586b4 lib: update libmetal to SHA 23ba77941cf3
> === updating liblc3codec (modules/lib/liblc3codec):
> HEAD is now at 3951cf1 Add liblc3 as a zephyr module
> === updating littlefs (modules/fs/littlefs):
> HEAD is now at 652f2c5 zephyr: update include paths to use <zephyr/...>
> === updating loramac-node (modules/lib/loramac-node):
> HEAD is now at 0257b509 zephyr: radio: sx127x: override buffer read/write functions
> === updating lvgl (modules/lib/gui/lvgl):
> HEAD is now at 487bcde7 zephyr: Pick up display resolution from device tree
> === updating lz4 (modules/lib/lz4):
> HEAD is now at 8e303c2 zephyr: make this repo a zephyr module
> === updating mbedtls (modules/crypto/mbedtls):
> HEAD is now at 7fed49c9b CC3XX: Hardcode entry points for the CC3XX driver
> === updating mipi-sys-t (modules/debug/mipi-sys-t):
> HEAD is now at a5163c1 library: fix compiler warning when wchar_t is 16-bit
> === updating nanopb (modules/lib/nanopb):
> HEAD is now at dc4deed Merge pull request #1 from pdgendt/zephyr
> === updating net-tools (tools/net-tools):
> HEAD is now at e0828aa net-setup: Add instructions for NAT and routing
> === updating nrf_hw_models (modules/bsim_hw_models/nrf_hw_models):
> HEAD is now at 9340626 ci: Add building the HW models as a github workflow
> === updating open-amp (modules/lib/open-amp):
> HEAD is now at 8d53544 lib: update open-amp lib to release v2022.04.0
> === updating picolibc (modules/lib/picolibc):
> HEAD is now at e87b2fc37 cmake: Allow setting of __PICOLIBC_ERRNO_FUNCTION
> === updating segger (modules/debug/segger):
> HEAD is now at d4e568a Resolve circular include dependencies
> === updating tinycbor (modules/lib/tinycbor):
> HEAD is now at 9e1f34b module: Deprecate TinyCBOR
> === updating tinycrypt (modules/crypto/tinycrypt):
> HEAD is now at 3e9a49d cmake: Fix conditional in root CMakeLists.txt
> === updating TraceRecorderSource (modules/debug/TraceRecorder):
> HEAD is now at 9893bf1 Merge pull request #8 from tleksell-pe/trace_recorder_4.6.3_update
> === updating tf-m-tests (modules/tee/tf-m/tf-m-tests):
> HEAD is now at c99a86b Merge pull request #2 from theotherjimmy/update-tfm-pre-1.6.0
> === updating psa-arch-tests (modules/tee/tf-m/psa-arch-tests):
> HEAD is now at f4fc244 Merge pull request #5 from Vge0rge/increase_crypto_timeout
> === updating zcbor (modules/lib/zcbor):
> HEAD is now at a0d6981 Update version from 0.5.99 to 0.5.1
> === updating zscilib (modules/lib/zscilib):
> HEAD is now at a54986a Merge pull request #35 from uLipe/bugfix/mahony_pi_windup
>  *  Terminal will be reused by tasks, press any key to close it. 

```
`manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      remote: ncs
      path: nrf
      revision: v2.1.99-dev2
      import: true
      clone-depth: 1
    - name: HX711
      path: modules/HX711
      revision: main
      url: https://github.com/nobodyguy/HX711_zephyr_driver
  self:
    path: attempt_hr`
```

After updating the proj.conf I'm getting unknown symbol for CONFIG_HX711

looking in the build\modules folder I'd expect to see the HX711 folder there but I don't. 

Possibly this is something with my project configuration since i do find it one level up in and in that modules folder 

![image](https://user-images.githubusercontent.com/2816202/200748414-59e76e99-a3ac-4c94-913c-e6949f257c9e.png)

**Comment by nobodyguy** [comment]
Hello, thank you for the report.
That's correct behavior of west, it fetches all the modules to a root folder (your app is also just a module).
You are also using unsupported version of Zephyr [v3.2.0](https://github.com/zephyrproject-rtos/zephyr/releases/tag/v3.2.0), I think they changed a few things like driver macros and include paths, so it won't work.
You can either try to use this fork https://github.com/yanagiis/HX711_zephyr_driver/commit/cc6319c3c9384fb81bc0d4098c41b4ec218b6a3f or wait until I review and test the changes and update this driver.

**Comment by twonius** [comment]
thanks that fork helped but I'm still seeing an error on this line of the example code when i try to compile 
`
	hx711 = DEVICE_DT_GET(DT_ALIAS(hx711_sensor));
`
> > ../src/main.c: In function 'main':
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:96:39: error: '__device_dts_ord_DT_N_ALIAS_hx711_sensor_ORD' undeclared (first use in this function)
>    96 | #define DEVICE_NAME_GET(name) _CONCAT(__device_, name)
>       |                                       ^~~~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\toolchain\common.h:132:26: note: in definition of macro '_DO_CONCAT'
>   132 | #define _DO_CONCAT(x, y) x ## y
>       |                          ^
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:96:31: note: in expansion of macro '_CONCAT'
>    96 | #define DEVICE_NAME_GET(name) _CONCAT(__device_, name)
>       |                               ^~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:276:37: note: in expansion of macro 'DEVICE_NAME_GET'
>   276 | #define DEVICE_DT_NAME_GET(node_id) DEVICE_NAME_GET(Z_DEVICE_DT_DEV_NAME(node_id))
>       |                                     ^~~~~~~~~~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:296:34: note: in expansion of macro 'DEVICE_DT_NAME_GET'
>   296 | #define DEVICE_DT_GET(node_id) (&DEVICE_DT_NAME_GET(node_id))
>       |                                  ^~~~~~~~~~~~~~~~~~
> c:\Users\anton\Desktop\NrfTest\Attempt9\hello_world\src\main.c:42:10: note: in expansion of macro 'DEVICE_DT_GET'
>    42 |  hx711 = DEVICE_DT_GET(DT_ALIAS(hx711_sensor));
>       |          ^~~~~~~~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:96:39: note: each undeclared identifier is reported only once for each function it appears in
>    96 | #define DEVICE_NAME_GET(name) _CONCAT(__device_, name)
>       |                                       ^~~~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\toolchain\common.h:132:26: note: in definition of macro '_DO_CONCAT'
>   132 | #define _DO_CONCAT(x, y) x ## y
>       |                          ^
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:96:31: note: in expansion of macro '_CONCAT'
>    96 | #define DEVICE_NAME_GET(name) _CONCAT(__device_, name)
>       |                               ^~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:276:37: note: in expansion of macro 'DEVICE_NAME_GET'
>   276 | #define DEVICE_DT_NAME_GET(node_id) DEVICE_NAME_GET(Z_DEVICE_DT_DEV_NAME(node_id))
>       |                                     ^~~~~~~~~~~~~~~
> C:\Users\anton\Desktop\NrfTest\Attempt9\zephyr\include\zephyr\device.h:296:34: note: in expansion of macro 'DEVICE_DT_NAME_GET'
>   296 | #define DEVICE_DT_GET(node_id) (&DEVICE_DT_NAME_GET(node_id))
>       |                                  ^~~~~~~~~~~~~~~~~~
> c:\Users\anton\Desktop\NrfTest\Attempt9\hello_world\src\main.c:42:10: note: in expansion of macro 'DEVICE_DT_GET'
>    42 |  hx711 = DEVICE_DT_GET(DT_ALIAS(hx711_sensor));
>       |          ^~~~~~~~~~~~~

**Comment by nobodyguy** [comment]
As I wrote, they changed these things in newer Zephyr versions.
You used updated driver fork, but also the example code needs to be updated accordingly.
Try other device tree macros like DT_NODELABEL or similar.
Untested example:
```c
#include <device.h>
#include <drivers/sensor.h>
#include <sensor/hx711/hx711.h>
#include <logging/log.h>
#include <stddef.h>
#include <sys/util.h>
#include <zephyr/types.h>

LOG_MODULE_REGISTER(main, LOG_LEVEL_INF);

const struct device *hx711_dev;

void set_rate(enum hx711_rate rate)
{
	static struct sensor_value rate_val;

	rate_val.val1 = rate;
	sensor_attr_set(hx711_dev,
			HX711_SENSOR_CHAN_WEIGHT,
			SENSOR_ATTR_SAMPLING_FREQUENCY,
			&rate_val);
}

void measure(void)
{
	static struct sensor_value weight;
	int ret;

	ret = sensor_sample_fetch(hx711_dev);
	if (ret != 0) {
		LOG_ERR("Cannot take measurement: %d", ret);
	} else {
		sensor_channel_get(hx711_dev, HX711_SENSOR_CHAN_WEIGHT, &weight);
		LOG_INF("Weight: %d.%06d grams", weight.val1, weight.val2);
	}
}

void main(void)
{
	int calibration_weight = 100; // grams
	hx711_dev = DEVICE_DT_GET(DT_NODELABEL(hx711));
	__ASSERT(hx711_dev == NULL, "Failed to get device binding");

	LOG_INF("Device is %p, name is %s", hx711_dev, hx711_dev->name);
	LOG_INF("Calculating offset...");
	avia_hx711_tare(hx711_dev, 5);

	LOG_INF("Waiting for known weight of %d grams...",
		calibration_weight);

	for (int i = 5; i >= 0; i--) {
		LOG_INF(" %d..", i);
		k_msleep(1000);
	}

	LOG_INF("Calculating slope...");
	avia_hx711_calibrate(hx711_dev, calibration_weight, 5);

	while (true) {
		k_msleep(1000);
		LOG_INF("== Test measure ==");
		LOG_INF("= Setting sampling rate to 10Hz.");
		set_rate(HX711_RATE_10HZ);
		measure();

		k_msleep(1000);
		LOG_INF("= Setting sampling rate to 80Hz.");
		set_rate(HX711_RATE_80HZ);
		measure();
	}
}
```

**Comment by twonius** [comment]
thanks, 

I dug a bit more into the [devicetree documentation](https://docs.zephyrproject.org/3.2.0/build/dts/howtos.html) and tried replacing the line in question with `hx711_dev = device_get_binding("hx711");`

This got me a bit further in the compile (I ended up having to run vs code as administrator but that's tangential) 

after that I ran into  an error in 

> C:/Users/anton/Desktop/NrfTest/Attempt9/modules/HX711/drivers/sensor/hx711/hx711.c: In function 'hx711_attr_set_rate':
> C:\Users\anton\Desktop\NrfTest\Attempt9\modules\HX711\drivers\sensor\hx711\hx711.c:193:39: error: 'hx711_config' undeclared (first use in this function)
>   193 |   ret = gpio_pin_set(data->rate_gpio, hx711_config.rate_pin,
 
 and 
 

> C:/Users/anton/Desktop/NrfTest/Attempt9/modules/HX711/drivers/sensor/hx711/hx711.c: In function 'hx711_init':
> C:\Users\anton\Desktop\NrfTest\Attempt9\modules\HX711\drivers\sensor\hx711\hx711.c:348:10: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'const struct device * const' [-Wformat=]
>   348 |  LOG_DBG("RATE GPIO port : %s\n", cfg->rate_ctrl);
>       |          ^~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~
>       |                                      |
>       |                                      const struct device * const 
>

**Comment by twonius** [comment]
digging a bit more this evening I think the issue is here. it's not not initializing hx711_config because 

`DT_INST_FOREACH_STATUS_OKAY(SENSOR_HX711_INIT)`

[{
	"resource": "/c:/Users/anton/Desktop/NrfTest/Attempt9/modules/HX711/drivers/sensor/hx711/hx711.c",
	"owner": "C/C++",
	"code": "54",
	"severity": 8,
	"message": "too few arguments in invocation of macro \"Z_FOR_LOOP_1\"",
	"source": "C/C++",
	"startLineNumber": 606,
	"startColumn": 1,
	"endLineNumber": 606,
	"endColumn": 28
}]

**Comment by nobodyguy** [comment]
Got it working with Zephyr v3.2.0, but I don't have time to properly test it and push it right now (vacation). So I'll test is and hopefully release the new version on Monday.

**Comment by nobodyguy** [comment]
If you want to test it meanwhile, here is the git patch:
```diff
diff --git a/drivers/sensor/hx711/hx711.c b/drivers/sensor/hx711/hx711.c
index b7adf9d..ca9af6c 100644
--- a/drivers/sensor/hx711/hx711.c
+++ b/drivers/sensor/hx711/hx711.c
@@ -1,20 +1,17 @@
 /*
  * Copyright (c) 2020 George Gkinis
- * Copyright (c) 2021 Jan Gnip
+ * Copyright (c) 2022 Jan Gnip
  * SPDX-License-Identifier: Apache-2.0
  */
 
 #define DT_DRV_COMPAT avia_hx711
 
-#include <device.h>
-#include <drivers/gpio.h>
-#include <sys/byteorder.h>
-#include <drivers/sensor.h>
-#include <string.h>
-#include <zephyr.h>
-#include <logging/log.h>
-
-#include <irq.h>
+#include <zephyr/device.h>
+#include <zephyr/drivers/gpio.h>
+#include <zephyr/drivers/sensor.h>
+#include <zephyr/irq.h>
+#include <zephyr/logging/log.h>
+#include <zephyr/sys/byteorder.h>
 
 #include "hx711.h"
 
@@ -36,16 +33,16 @@ static struct hx711_data hx711_data = {
 
 static const struct hx711_config hx711_config = {
 	.dout_pin = DT_INST_GPIO_PIN(0, dout_gpios),
-	.dout_ctrl = DT_INST_GPIO_LABEL(0, dout_gpios),
+	.dout_ctrl = DEVICE_DT_GET(DT_GPIO_CTLR(DT_DRV_INST(0), dout_gpios)),
 	.dout_flags = DT_INST_GPIO_FLAGS(0, dout_gpios),
 
 	.sck_pin = DT_INST_GPIO_PIN(0, sck_gpios),
-	.sck_ctrl = DT_INST_GPIO_LABEL(0, sck_gpios),
+	.sck_ctrl = DEVICE_DT_GET(DT_GPIO_CTLR(DT_DRV_INST(0), sck_gpios)),
 	.sck_flags = DT_INST_GPIO_FLAGS(0, sck_gpios),
 
 #if DT_INST_NODE_HAS_PROP(0, rate_gpios)
 	.rate_pin = DT_INST_GPIO_PIN(0, rate_gpios),
-	.rate_ctrl = DT_INST_GPIO_LABEL(0, rate_gpios),
+	.rate_ctrl = DEVICE_DT_GET(DT_GPIO_CTLR(DT_DRV_INST(0), rate_gpios)),
 	.rate_flags = DT_INST_GPIO_FLAGS(0, rate_gpios),
 #endif
 
@@ -206,8 +203,7 @@ static int hx711_attr_set_rate(struct hx711_data *data, const struct sensor_valu
 	case HX711_RATE_10HZ:
 	case HX711_RATE_80HZ:
 		if (data->rate_gpio == NULL) {
-			LOG_ERR("Failed to get pointer to RATE device: %s",
-				DT_INST_GPIO_LABEL(0, rate_gpios));
+			LOG_ERR("Failed to get pointer to RATE device");
 			return -EINVAL;
 		}
 		data->rate = val->val1;
@@ -355,13 +351,13 @@ static int hx711_init(const struct device *dev)
 	struct hx711_data *data = dev->data;
 	const struct hx711_config *cfg = dev->config;
 
-	LOG_DBG("SCK GPIO port : %s\n", cfg->sck_ctrl);
+	LOG_DBG("SCK GPIO port : %s\n", cfg->sck_ctrl->name);
 	LOG_DBG("SCK Pin : %d\n", cfg->sck_pin);
-	LOG_DBG("DOUT GPIO port : %s\n", cfg->dout_ctrl);
+	LOG_DBG("DOUT GPIO port : %s\n", cfg->dout_ctrl->name);
 	LOG_DBG("DOUT Pin : %d\n", cfg->dout_pin);
 
 #if DT_INST_NODE_HAS_PROP(0, rate_gpios)
-	LOG_DBG("RATE GPIO port : %s\n", cfg->rate_ctrl);
+	LOG_DBG("RATE GPIO port : %s\n", cfg->rate_ctrl->name);
 	LOG_DBG("RATE Pin : %d\n", cfg->rate_pin);
 #endif
 
@@ -370,11 +366,7 @@ static int hx711_init(const struct device *dev)
 	LOG_DBG("Slope : %d.%d\n", data->slope.val1, data->slope.val2);
 
 	/* Configure SCK as output, LOW */
-	data->sck_gpio = device_get_binding(cfg->sck_ctrl);
-	if (data->sck_gpio == NULL) {
-		LOG_ERR("Failed to get GPIO device %s.", cfg->sck_ctrl);
-		return -EINVAL;
-	}
+	data->sck_gpio = cfg->sck_ctrl;
 	LOG_DBG("SCK pin controller is %p, name is %s\n", data->sck_gpio, data->sck_gpio->name);
 
 	ret = gpio_pin_configure(data->sck_gpio, cfg->sck_pin,
@@ -385,9 +377,9 @@ static int hx711_init(const struct device *dev)
 
 #if DT_INST_NODE_HAS_PROP(0, rate_gpios)
 	/* Configure RATE as output, LOW */
-	data->rate_gpio = device_get_binding(cfg->rate_ctrl);
+	data->rate_gpio = device_get_binding(cfg->rate_ctrl->name);
 	if (data->rate_gpio == NULL) {
-		LOG_ERR("Failed to get GPIO device %s.", cfg->rate_ctrl);
+		LOG_ERR("Failed to get GPIO device %s.", cfg->rate_ctrl->name);
 		return -EINVAL;
 	}
 	LOG_DBG("RATE pin controller is %p, name is %s\n", data->rate_gpio, data->rate_gpio->name);
@@ -406,12 +398,7 @@ static int hx711_init(const struct device *dev)
 	k_sem_init(&data->dout_sem, 1, 1);
 
 	/* Configure DOUT as input */
-	data->dout_gpio = device_get_binding(cfg->dout_ctrl);
-	if (data->dout_gpio == NULL) {
-		LOG_ERR("Failed to get GPIO device %s.", cfg->dout_ctrl);
-		return -EINVAL;
-	}
-
+	data->dout_gpio = cfg->sck_ctrl;
 	LOG_DBG("DOUT pin controller is %p, name is %s\n", data->dout_gpio, data->dout_gpio->name);
 	ret = gpio_pin_configure(data->dout_gpio, cfg->dout_pin, GPIO_INPUT | cfg->dout_flags);
 	if (ret != 0) {
diff --git a/drivers/sensor/hx711/hx711.h b/drivers/sensor/hx711/hx711.h
index 8aa80c0..2bff692 100644
--- a/drivers/sensor/hx711/hx711.h
+++ b/drivers/sensor/hx711/hx711.h
@@ -1,6 +1,6 @@
 /*
  * Copyright (c) 2020 George Gkinis
- * Copyright (c) 2021 Jan Gnip
+ * Copyright (c) 2022 Jan Gnip
  * SPDX-License-Identifier: Apache-2.0
  */
 
@@ -11,10 +11,10 @@
 extern "C" {
 #endif
 
-#include <device.h>
-#include <kernel.h>
-#include <drivers/sensor.h>
-#include <drivers/gpio.h>
+#include <zephyr/device.h>
+#include <zephyr/kernel.h>
+#include <zephyr/drivers/sensor.h>
+#include <zephyr/drivers/gpio.h>
 
 /* Additional custom attributes */
 enum hx711_attribute {
@@ -61,15 +61,15 @@ struct hx711_data {
 
 struct hx711_config {
 	gpio_pin_t dout_pin;
-	const char *dout_ctrl;
+	const struct device *dout_ctrl;
 	gpio_dt_flags_t dout_flags;
 
 	gpio_pin_t sck_pin;
-	const char *sck_ctrl;
+	const struct device *sck_ctrl;
 	gpio_dt_flags_t sck_flags;
 
 	gpio_pin_t rate_pin;
-	const char *rate_ctrl;
+	const struct device *rate_ctrl;
 	gpio_dt_flags_t rate_flags;
 };
 
diff --git a/dts/bindings/sensor/avia,hx711.yaml b/dts/bindings/sensor/avia,hx711.yaml
index ef3c628..47be1b8 100644
--- a/dts/bindings/sensor/avia,hx711.yaml
+++ b/dts/bindings/sensor/avia,hx711.yaml
@@ -1,5 +1,5 @@
 # Copyright (c) 2020 George Gkinis
-# Copyright (c) 2021 Jan Gnip
+# Copyright (c) 2022 Jan Gnip
 # SPDX-License-Identifier: Apache-2.0
 
 description: |
@@ -27,7 +27,4 @@ properties:
     type: phandle-array
     required: false
     description: |
-      Pin on which sampling rate is chosen.
-
-  label:
-    required: true
\ No newline at end of file
+      Pin on which sampling rate is chosen.
\ No newline at end of file

```

**Comment by twonius** [comment]
it now compiles with the patch. 

Thanks for continuing to support this code.

**Comment by nobodyguy** [comment]
Tested and merged. See the updated readme.

**Comment by henriquet22** [comment]
I'm sorry, I still have a lot of trouble trying to use this code, can i ask your help?
